- name: Create the VM with Static IP
  hosts: localhost
  gather_facts: false
    
  tasks:
    - name: Create the VM
      community.vmware.vmware_guest:
        hostname: "localhost.localdomain"
        username: "root"
        password: "Datait2024!"
        validate_certs: no
        folder: "/VM/"
        name: "AnsibleDeployedMachine"
        state: "poweredon"
        guest_id: "ubuntu64Guest"
        esxi_hostname: "192.168.20.20"
        disk:
          - size_gb: "30"
            type: "thin"
            datastore: "DataStore"
        hardware:
          memory_mb: "4000"
          num_cpus: "2"
        networks:
          - name: "vm-network"
            start_connected: true
        cdrom:
          type: "iso"
          iso_path: "[DataStore] ISO/ubuntu-24.04.1-live-server-amd64.iso"
