- name: Verify Python and pyVmomi
  hosts: localhost
  tasks:
    - name: Show Python version
      ansible.builtin.command:
        cmd: python3 --version
      register: python_version
    - debug:
        msg: "Python version: {{ python_version.stdout }}"

    - name: List installed pip packages
      ansible.builtin.command:
        cmd: python3.12 -m pip list
      register: pip_list
    - debug:
        msg: "Pip packages: {{ pip_list.stdout_lines }}"

    - name: Verify Ansible Python interpreter
      debug:
        msg: "Ansible is using {{ ansible_python.version.full }} at {{ ansible_python.interpreter }}"
