- name: Check Python Interpreter
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Display Python Interpreter Path
      debug:
        msg: "Python interpreter being used is {{ ansible_python_interpreter }}"
