- name: Create Meta-Data, Cloud-Init ISO, and Deploy VM with Ubuntu Gnome
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: "AnsibleDeployedMachineTest103"
    iso_path: "/home/gruppe2/AnsibleDeployments/cloud-init.iso"
    esxi_iso_path: "ISO/ubuntu-24.04.1-live-server-amd64.iso"
    esxi_hostname: "192.168.20.10"
    esxi_username: "root"
    esxi_password: "Datait2024!"
    guest_id: "ubuntu64Guest"
    datastore: "DataStore"
    vm_network: "VM Network"
    vm_ip: "192.168.20.81"
    vm_memory_mb: 4000
    vm_cpus: 2

  tasks:
    - name: Create the Virtual Machine with Ubuntu ISO
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: "/"
        name: "{{ vm_name }}"
        state: "powered-off"
        guest_id: "{{ guest_id }}"
        disk:
          - size_gb: 30
            type: thin
            datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_cpus }}"
        networks:
          - name: "{{ vm_network }}"
            type: static
            ip: "{{ vm_ip }}"
            netmask: "255.255.255.0"
            gateway: "192.168.20.1"
            dns_servers:
              - "8.8.8.8"
        cdrom:
          - controller_number: 0
            unit_number: 0
            state: present
            type: iso
            iso_path: "[DataStore] {{ esxi_iso_path }}"

    - name: Power On the Virtual Machine with Ubuntu ISO
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: "/"
        name: "{{ vm_name }}"
        state: "powered-on"
