- name: Verify Python 3.12 and pyVmomi
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check Python version
      ansible.builtin.command:
        cmd: python3.12 --version
      register: python_version
    - debug:
        msg: "Python version: {{ python_version.stdout }}"

    - name: Test pyVmomi JSONEncoder
      ansible.builtin.command:
        cmd: python3.12 -c "from pyVmomi.VmomiSupport import VmomiJSONEncoder; print('VmomiJSONEncoder works!')"
      register: pyvmomi_test
      failed_when: pyvmomi_test.rc != 0
    - debug:
        msg: "pyVmomi Test Output: {{ pyvmomi_test.stdout }}"
