- name: Verify Python Environment
  hosts: localhost
  gather_facts: true  # Enable fact gathering

  tasks:
    - name: Verify Python version
      ansible.builtin.command:
        cmd: python3 --version
      register: python_version
    - debug:
        msg: "Python version: {{ python_version.stdout }}"

    - name: Verify installed pip packages
      ansible.builtin.shell:
        cmd: python3.12 -m pip list
      register: pip_list
    - debug:
        msg: "Installed pip packages:\n{{ pip_list.stdout_lines }}"

    - name: Verify Ansible Python interpreter
      debug:
        msg: "Ansible is using interpreter {{ ansible_python.interpreter }}"

    - name: Create a file locally with Python info
      ansible.builtin.copy:
        content: |
          Python Version: {{ python_version.stdout }}
          Installed Pip Packages:
          {{ pip_list.stdout_lines | join('\n') }}
          Ansible Python Interpreter: {{ ansible_python.interpreter }}
        dest: ./pythoninfo.txt
