    - name: Fetch ESXi facts
      community.vmware.vmware_host_facts:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
      register: esxi_facts

    - name: Debug ESXi facts
      ansible.builtin.debug:
        var: esxi_facts
