- name: Minimal Test Playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Test VMware Connection
      community.vmware.vmware_guest:
        hostname: "192.168.20.10"
        username: "root"
        password: "Datait2024!"
        validate_certs: no
        folder: "/"
        name: "TestVM"
        state: "absent"  # Change this to "present" if you want to create the VM
