- name: Verify Python Environment
  hosts: localhost
  gather_facts: true  # Ensure facts are gathered to populate ansible_python

  tasks:
    - name: Verify Python version
      ansible.builtin.command:
        cmd: python3 --version
      register: python_version
    - debug:
        msg: "Python version: {{ python_version.stdout }}"

    - name: Verify installed pip packages
      ansible.builtin.shell:
        cmd: python3.12 -m pip list
      register: pip_list
    - debug:
        msg: "Installed pip packages:\n{{ pip_list.stdout_lines }}"

    - name: Verify Ansible Python version and location
      debug:
        msg: >
          Ansible is using Python version {{ ansible_facts.python.version.full }}
          located at {{ ansible_facts.python.executable }}
