- name: Simulate VM Creation
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: "AnsibleDeployedMachine10Test"
    user_data_path: "/home/gruppe2/AnsibleDeployments/user-data"
    meta_data_path: "/home/gruppe2/AnsibleDeployments/meta-data"
    iso_path: "/home/gruppe2/AnsibleDeployments/cloud-init.iso"
    esxi_iso_path: "[Datastore] Ansible/Cloud/cloud-init.iso"

  tasks:
    - name: Generate meta-data file dynamically
      copy:
        dest: "{{ meta_data_path }}"
        content: |
          instance-id: "{{ vm_name }}"
          local-hostname: "{{ vm_name }}"

    - name: Create Cloud-Init ISO
      ansible.builtin.command:
        cmd: >
          genisoimage -output "{{ iso_path }}"
          -volid cidata -joliet -rock
          "{{ user_data_path }}" "{{ meta_data_path }}"

    - name: Simulate moving Cloud-Init ISO to ESXi server
      ansible.builtin.debug:
        msg: >
          Simulating copy of "{{ iso_path }}"
          to ESXi server at "{{ esxi_iso_path }}"

